"""Reset Full Schema

Revision ID: faea908d11f5
Revises: 
Create Date: 2025-12-30 10:34:50.150292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faea908d11f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materiels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=True),
    sa.Column('modele', sa.String(length=100), nullable=True),
    sa.Column('sn', sa.String(length=100), nullable=True),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('imei', sa.String(length=100), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sn')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('fullname', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('USER', 'MANAGER', 'ADMIN', 'SOLVER', name='userrole'), nullable=True),
    sa.Column('service_department', sa.Enum('INFO', 'DAF', 'GEN', 'TECH', 'ENLEV', name='servicetype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materiel_id', sa.Integer(), nullable=True),
    sa.Column('technicien_id', sa.Integer(), nullable=True),
    sa.Column('nom_emprunteur', sa.String(length=100), nullable=True),
    sa.Column('prenom_emprunteur', sa.String(length=100), nullable=True),
    sa.Column('service_emprunteur', sa.String(length=100), nullable=True),
    sa.Column('date_sortie', sa.DateTime(), nullable=True),
    sa.Column('date_retour_prevue', sa.DateTime(), nullable=True),
    sa.Column('date_retour_reelle', sa.DateTime(), nullable=True),
    sa.Column('statut_dossier', sa.String(length=20), nullable=True),
    sa.Column('type_pret', sa.String(length=50), nullable=True),
    sa.Column('accessoires', sa.String(length=255), nullable=True),
    sa.Column('etat_ecran_sortie', sa.String(length=50), nullable=True),
    sa.Column('etat_clavier_sortie', sa.String(length=50), nullable=True),
    sa.Column('etat_coque_sortie', sa.String(length=50), nullable=True),
    sa.Column('etat_ecran_retour', sa.String(length=50), nullable=True),
    sa.Column('etat_clavier_retour', sa.String(length=50), nullable=True),
    sa.Column('etat_coque_retour', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['materiel_id'], ['materiels.id'], ),
    sa.ForeignKeyConstraint(['technicien_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.Enum('INFO', 'DAF', 'GEN', 'TECH', 'ENLEV', name='servicetype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid_public', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('target_service', sa.Enum('INFO', 'DAF', 'GEN', 'TECH', 'ENLEV', name='servicetype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATION', 'PENDING', 'IN_PROGRESS', 'REFUSED', 'DONE', name='ticketstatus'), nullable=True),
    sa.Column('solver_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('category_ticket', sa.String(length=50), nullable=True),
    sa.Column('hostname', sa.String(length=64), nullable=True),
    sa.Column('service_demandeur', sa.String(length=100), nullable=True),
    sa.Column('tel_demandeur', sa.String(length=20), nullable=True),
    sa.Column('lieu_installation', sa.String(length=100), nullable=True),
    sa.Column('new_user_fullname', sa.String(length=150), nullable=True),
    sa.Column('new_user_service', sa.String(length=100), nullable=True),
    sa.Column('new_user_acces', sa.String(length=255), nullable=True),
    sa.Column('new_user_date', sa.DateTime(), nullable=True),
    sa.Column('materiel_list', sa.Text(), nullable=True),
    sa.Column('destinataire_materiel', sa.String(length=150), nullable=True),
    sa.Column('service_destinataire', sa.String(length=100), nullable=True),
    sa.Column('daf_lieu_livraison', sa.String(length=100), nullable=True),
    sa.Column('daf_fournisseur_nom', sa.String(length=100), nullable=True),
    sa.Column('daf_fournisseur_tel', sa.String(length=50), nullable=True),
    sa.Column('daf_fournisseur_fax', sa.String(length=50), nullable=True),
    sa.Column('daf_fournisseur_email', sa.String(length=100), nullable=True),
    sa.Column('daf_type_prix', sa.String(length=10), nullable=True),
    sa.Column('daf_lignes_json', sa.Text(), nullable=True),
    sa.Column('daf_files_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['solver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_uid_public'), ['uid_public'], unique=True)

    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_messages')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_uid_public'))

    op.drop_table('tickets')
    op.drop_table('team_messages')
    op.drop_table('prets')
    op.drop_table('notifications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('materiels')
    # ### end Alembic commands ###
